# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spreadsheet-ParseExcel
version:      0.40
version_from: lib/Spreadsheet/ParseExcel.pm
installdirs:  site
requires:
    IO::File:                      0
    IO::Scalar:                    0
    OLE::Storage_Lite:             0.08
    Scalar::Util:                  0
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
