--- #YAML:1.0
name: Spreadsheet-ParseExcel
version: 0.27_02
author:
  - Kawai Takanori
abstract: Get information from Excel file
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
